export const allTextureKeys = {
  asteroid: "asteroid",
  asteroid1: "asteroid1",
  asteroid2: "asteroid2",
  asteroid3: "asteroid3",
  asteroid4: "asteroid4",
  wariorSpaseShip: "wariorSpaseShip",
  bomb: "bomb",
  musicOn: "musicOn",
  musicOff: "musicOff",
  effectsOn: "effectsOn",
  effectsOff: "effectsOff",
  enemyShip: "enemyShip",
  man: "man",
  man2: "man2",
  woman: "woman",
  TombStone1: "TombStone1",
  TombStone2: "TombStone2",
  spaceShip: "spaceShip",
  bullet1: "bullet1",
  bullet2: "bullet2",
  bulletInfo: " bulletInfo",
  explosion: "explosion",
  explosion1: "explosion1",
  explosion2: "explosion2",
  explosion3: "explosion3",
  hourglass: 'hourglass',
};

const appTextures = {
  [allTextureKeys.asteroid]: "assets/sprites/enemys/asteroid.png",
  [allTextureKeys.asteroid1]: "assets/sprites/enemys/asteroid1.png",
  [allTextureKeys.asteroid2]: "assets/sprites/enemys/asteroid2.png",
  [allTextureKeys.asteroid3]: "assets/sprites/enemys/asteroid3.png",
  [allTextureKeys.asteroid4]: "assets/sprites/enemys/asteroid4.png",
  [allTextureKeys.wariorSpaseShip]: "assets/sprites/enemys/wariorSpaseShip.png",
  [allTextureKeys.bomb]: "assets/sprites/bomb.png",
  [allTextureKeys.musicOn]: "assets/sprites/ui/music_on.png",
  [allTextureKeys.musicOff]: "assets/sprites/ui/music_off.png",
  [allTextureKeys.effectsOn]: "assets/sprites/ui/volume_on.png",
  [allTextureKeys.effectsOff]: "assets/sprites/ui/volume_off.png",
  [allTextureKeys.enemyShip]: "assets/sprites/enemys/wariorSpaseShip.png",
  [allTextureKeys.man]: "assets/sprites/people/man.png",
  [allTextureKeys.man2]: "assets/sprites/people/man2.png",
  [allTextureKeys.woman]: "assets/sprites/people/woman.png",
  [allTextureKeys.TombStone1]: "assets/sprites/people/TombStone1.png",
  [allTextureKeys.TombStone2]: "assets/sprites/people/TombStone2.png",
  [allTextureKeys.spaceShip]: "assets/sprites/player.png",
  [allTextureKeys.bullet1]: "assets/sprites/bullets/bullet1.json",
  [allTextureKeys.bullet2]: "assets/sprites/bullets/bullet2.json",
  [allTextureKeys.bulletInfo]: "assets/sprites/bullets/bulletInfo.png",
  [allTextureKeys.explosion]: "assets/sprites/explosion/explosion.json",
  [allTextureKeys.explosion1]: "assets/sprites/explosion/explosion1.json",
  [allTextureKeys.explosion2]: "assets/sprites/explosion/explosion2.json",
  [allTextureKeys.explosion3]: "assets/sprites/explosion/explosion3.json",
  [allTextureKeys.hourglass]: "assets/sprites/ui/hourglass.png",
};

export default appTextures;
